pipeline {
    agent any
    environment {
        REPO_URL       = 'https://github.com/Viraj2405/Webhook'
        BRANCH     = 'main'
        FILE_NAME      = 'Pipedrive API v1.json'
        TEMP_DIR       = 'temp-repo'
        SECURITY_SCAN_API = 'https://fbbc-45-252-74-134.ngrok-free.app/v1/startSecurityScan'
        PROJECT_ID     = 'e9914d12-723a-4afd-82f3-6816b9b812a7'
        BLOCK_PIPELINE = 'true'
        BLOCK_CRITICAL = 'false'
        BLOCK_HIGH     = 'false'
        BLOCK_MEDIUM   = 'false'
        CRITICAL_THRESHOLD = '0'
        HIGH_THRESHOLD     = '0'
        MEDIUM_THRESHOLD   = '0'
        INTEGRATION_ID = '387442b4-0d72-4edd-aacf-ceda6c46e1b7'
        UPLOAD_API_URL = 'https://fbbc-45-252-74-134.ngrok-free.app/v1/webHook'
    }

    stages {
        stage('Clone & Upload File') {
            steps {
                script {
                    bat """
                    git clone --branch %BRANCH% --depth 1 %REPO_URL% %TEMP_DIR%
                    for /f "delims=" %%F in ('dir /s /b %TEMP_DIR%\\%FILE_NAME%') do (
                        echo Found: %%F
                        copy "%%F" "%WORKSPACE%\\%FILE_NAME%"
                    )
                    rmdir /s /q %TEMP_DIR%
                    """

                    if (!fileExists("${env.FILE_NAME}")) {
                        error "File '${env.FILE_NAME}' not found after clone."
                    }

                    bat """
                    curl --location "%UPLOAD_API_URL%" ^
                    --form "file=@%FILE_NAME%" ^
                    --form "project_id=%PROJECT_ID%"
                    """
                }
            }
        }

        stage('Run Security Scan') {
            steps {
                script {
                    def response = bat(
                        script: """
                        curl --silent --request POST "%SECURITY_SCAN_API%/%PROJECT_ID%" ^
                        --header "Api-Key: %INTEGRATION_ID%"
                        """,
                        returnStdout: true
                    ).trim()

                    echo "Scan Response: ${response}"

                    if (response.contains('"message":"token expired"')) {
                        error "Token expired. Aborting pipeline."
                    }

                    def extractInt = { key ->
                        def match = (response =~ /"${key}"\\s*:\\s*(\\d+)/)
                        return match ? match[0][1].toInteger() : 0
                    }

                    def critical = extractInt('criticalCount')
                    def high     = extractInt('highCount')
                    def medium   = extractInt('mediumCount')

                    echo "Critical: ${critical}, High: ${high}, Medium: ${medium}"

                    if (env.BLOCK_PIPELINE == 'true') {
                        if (env.BLOCK_CRITICAL == 'true' && critical >= env.CRITICAL_THRESHOLD.toInteger()) {
                            error "Blocked: Critical findings exceed threshold."
                        }
                        if (env.BLOCK_HIGH == 'true' && high >= env.HIGH_THRESHOLD.toInteger()) {
                            error "Blocked: High findings exceed threshold."
                        }
                        if (env.BLOCK_MEDIUM == 'true' && medium >= env.MEDIUM_THRESHOLD.toInteger()) {
                            error "Blocked: Medium findings exceed threshold."
                        }
                        echo "No blocking issues. Continuing pipeline."
                    } else {
                        echo "Blocking is disabled."
                    }
                }
            }
        }

        stage('Post-processing') {
            steps {
                echo "Post-processing complete."
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
