name: Upload Changed Files

on:
  push:
    branches:
      - main

env:
  GIT_REPO: https://github.com/Viraj2405/Webhook.git
  GIT_BRANCH: main
  UPLOAD_API_URL: https://0858-45-252-74-134.ngrok-free.app/v1/webHook
  APPKEYTOKEN: 78e34aa639b94a8a5be22942b33e02f8
  PROJECT_ID: 41a7c1b1-e88d-4688-b61b-5bcd2e86abb3

jobs:
  upload-changed-files:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Identify Changed Files
        id: changes
        shell: pwsh
        run: |
          git fetch origin $env:GIT_BRANCH
          $changed = git diff --name-only HEAD~1 HEAD
          if (-not $changed) {
            throw "No files changed in the latest commit!"
          }
          $changedList = $changed -split "`r?`n" | Where-Object { $_ -ne "" }
          $changedList | ForEach-Object { Write-Host "Changed file: $_" }
          "CHANGED_FILES<<EOF" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          $changedList | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "EOF" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Upload Changed Files
        shell: pwsh
        run: |
          $files = $env:CHANGED_FILES -split "`r?`n" | Where-Object { $_ -ne "" }
          foreach ($file in $files) {
            if (Test-Path $file) {
              Write-Host "Uploading $file..."

              $escapedFile = $file -replace '"', '\"'
              $cmd = "curl --location `"$env:UPLOAD_API_URL`" --form `"file=@`"$escapedFile`"`" --form `"secret_key=$env:APPKEYTOKEN`" --form `"project_id=$env:PROJECT_ID`""

              Write-Host "Running curl for file: $file"
              iex $cmd
            } else {
              Write-Host "File not found (skipping): $file"
            }
          }

      - name: Post-processing
        run: echo "Upload stage completed."
