- name: Upload Changed Files
  shell: pwsh
  run: |
    $changedFiles = git diff --name-only HEAD~1 HEAD | Where-Object { $_ -ne "" }

    if (-not $changedFiles) {
      throw "No changed files found!"
    }

    foreach ($file in $changedFiles) {
      if (Test-Path $file) {
        Write-Host "Uploading $file..."

        $fileStream = [System.IO.FileStream]::new($file, [System.IO.FileMode]::Open, [System.IO.FileAccess]::Read)

        $response = Invoke-RestMethod -Uri "$env:UPLOAD_API_URL" -Method Post -Form @{
          file = $fileStream
          secret_key = "$env:APPKEYTOKEN"
          project_id = "$env:PROJECT_ID"
        }

        Write-Host "Upload response: $($response | ConvertTo-Json -Depth 5)"
      } else {
        Write-Host "File not found (skipping): $file"
      }
    }
